# Site settings
title: Arashi Blog
SEOTitle:  é›¨ç¼„ä¿¡ç¬º | Arashi Blog | ä¸å›è¿œç›¸çŸ¥,ä¸é“äº‘æµ·æ·±
header-img: img/home-bg.jpg
email: arashiizayoi@qq.com
description: "è¿™é‡Œæ˜¯ @åå…­å¤œå²š çš„ä¸ªäººåšå®¢ï¼Œä¸ä½ ä¸€èµ·å‘ç°æ›´å¤§çš„ä¸–ç•Œ | ä¸€ä¸ª çƒ­çˆ±ç”Ÿæ´» çš„ç¨‹åºå‘˜"
keyword: "å²š, Arashiå²š, Arashi, @Arashi, å²šçš„åšå®¢, Arashi Blog, åšå®¢, ä¸ªäººç½‘ç«™, äº’è”ç½‘, Web, JavaScript, Vue, å‰ç«¯, è®¾è®¡"
url: "https://arashiizayoi.xin/" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# å…¬å‘Šæ–‡ä»¶è·¯å¾„ï¼ˆç›¸å¯¹äºç«™ç‚¹æ ¹ç›®å½•ï¼‰
# å…¬å‘Šç³»ç»Ÿé…ç½®
announcement_path: "/announcements/am.md"

# æ„å»ºè®¾ç½®
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - "node_modules"
  - "Gemfile.lock"
# SNS settings
RSS: false
# weibo_username: 85767361
# zhihu_username: Arashipro
netease_username: 420371393
bilibili_username: 85767361
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
# disqus_username: Arashipro

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "G-ZZD4NR49SE" # Format: UA-xxxxxx-xx
ga_domain: arashiizayoi.xin

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "ä¸€ä¸ª çƒ­çˆ±ç”Ÿæ´» çš„ç¨‹åºå‘˜ <br> å‚²é›ªå‡Œéœœï¼Œè¸é›ªæ— ç—•<br>ğŸŒ ç¦å»º-ç¦å·"
sidebar-avatar: https://avatars.githubusercontent.com/u/107742034?s=96&v=4 # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    # { title: "ä¹±åºï¼ˆMidareï¼‰", href: "http://mida.re/" },
    # { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
    # { title: "Kun Qian", href: "http://kunq.me" },
    # { title: "Sherry Woo", href: "https://sherrywoo.me/" },
    # { title: "SmdCn", href: "http://blog.smdcn.net" },
    # { title: "JiyinYiyong", href: "http://tiye.me/" },
    # { title: "DHong Say", href: "http://dhong.co" },
    # { title: "å°¹å³°ä»¥ä¸º", href: "http://ingf.github.io/" },
  ]
